[window]
startup_mode = "Maximized"
padding = { x = 3, y = 3 }

[font]
size = 14
normal = { family = "GoMono Nerd Font", style = "Regular"}
bold = { family = "GoMono Nerd Font", style = "Bold"}
italic = { family = "GoMono Nerd Font", style = "Italic"}
bold_italic = { family = "GoMono Nerd Font", style = "Bold Italic"}
