#!/bin/bash

# Install Xcode cli tools
/bin/bash xcode-select --install

# Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Bash
brew install bash

# VS Code
brew install visual-studio-code

# nvim
brew install neovim

# Rectangle
brew install --cask rectangle

# treez man!
brew install tree

# Add bash profile to home directory, reference dotfile bashrc
touch ~/.bash_profile
echo "source ~/.dotfiles/bashrc" >> ~/.bash_profile

mv ~/.config/nvim ~/.config/nvim.backup
cp -a ~/.dotfiles/nvim/. ~/.config/nvim/

mv ~/.zprofile ~/.zprofile_old
